# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles /app//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named phase1_packet_usage

# Build rule for target.
phase1_packet_usage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 phase1_packet_usage
.PHONY : phase1_packet_usage

# fast build rule for target.
phase1_packet_usage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase1_packet_usage.dir/build.make CMakeFiles/phase1_packet_usage.dir/build
.PHONY : phase1_packet_usage/fast

#=============================================================================
# Target rules for targets named phase2_l2_parsing

# Build rule for target.
phase2_l2_parsing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 phase2_l2_parsing
.PHONY : phase2_l2_parsing

# fast build rule for target.
phase2_l2_parsing/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase2_l2_parsing.dir/build.make CMakeFiles/phase2_l2_parsing.dir/build
.PHONY : phase2_l2_parsing/fast

#=============================================================================
# Target rules for targets named phase3_fdb_usage

# Build rule for target.
phase3_fdb_usage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 phase3_fdb_usage
.PHONY : phase3_fdb_usage

# fast build rule for target.
phase3_fdb_usage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase3_fdb_usage.dir/build.make CMakeFiles/phase3_fdb_usage.dir/build
.PHONY : phase3_fdb_usage/fast

#=============================================================================
# Target rules for targets named phase4_interface_vlan_config

# Build rule for target.
phase4_interface_vlan_config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 phase4_interface_vlan_config
.PHONY : phase4_interface_vlan_config

# fast build rule for target.
phase4_interface_vlan_config/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase4_interface_vlan_config.dir/build.make CMakeFiles/phase4_interface_vlan_config.dir/build
.PHONY : phase4_interface_vlan_config/fast

#=============================================================================
# Target rules for targets named netflow_app

# Build rule for target.
netflow_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 netflow_app
.PHONY : netflow_app

# fast build rule for target.
netflow_app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netflow_app.dir/build.make CMakeFiles/netflow_app.dir/build
.PHONY : netflow_app/fast

#=============================================================================
# Target rules for targets named netflow_port_lib

# Build rule for target.
netflow_port_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 netflow_port_lib
.PHONY : netflow_port_lib

# fast build rule for target.
netflow_port_lib/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/netflow_port_lib.dir/build.make src/CMakeFiles/netflow_port_lib.dir/build
.PHONY : netflow_port_lib/fast

#=============================================================================
# Target rules for targets named netflow_switching_lib

# Build rule for target.
netflow_switching_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 netflow_switching_lib
.PHONY : netflow_switching_lib

# fast build rule for target.
netflow_switching_lib/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/netflow_switching_lib.dir/build.make src/CMakeFiles/netflow_switching_lib.dir/build
.PHONY : netflow_switching_lib/fast

examples/phase1_packet_usage.o: examples/phase1_packet_usage.cpp.o
.PHONY : examples/phase1_packet_usage.o

# target to build an object file
examples/phase1_packet_usage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase1_packet_usage.dir/build.make CMakeFiles/phase1_packet_usage.dir/examples/phase1_packet_usage.cpp.o
.PHONY : examples/phase1_packet_usage.cpp.o

examples/phase1_packet_usage.i: examples/phase1_packet_usage.cpp.i
.PHONY : examples/phase1_packet_usage.i

# target to preprocess a source file
examples/phase1_packet_usage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase1_packet_usage.dir/build.make CMakeFiles/phase1_packet_usage.dir/examples/phase1_packet_usage.cpp.i
.PHONY : examples/phase1_packet_usage.cpp.i

examples/phase1_packet_usage.s: examples/phase1_packet_usage.cpp.s
.PHONY : examples/phase1_packet_usage.s

# target to generate assembly for a file
examples/phase1_packet_usage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase1_packet_usage.dir/build.make CMakeFiles/phase1_packet_usage.dir/examples/phase1_packet_usage.cpp.s
.PHONY : examples/phase1_packet_usage.cpp.s

examples/phase2_l2_parsing.o: examples/phase2_l2_parsing.cpp.o
.PHONY : examples/phase2_l2_parsing.o

# target to build an object file
examples/phase2_l2_parsing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase2_l2_parsing.dir/build.make CMakeFiles/phase2_l2_parsing.dir/examples/phase2_l2_parsing.cpp.o
.PHONY : examples/phase2_l2_parsing.cpp.o

examples/phase2_l2_parsing.i: examples/phase2_l2_parsing.cpp.i
.PHONY : examples/phase2_l2_parsing.i

# target to preprocess a source file
examples/phase2_l2_parsing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase2_l2_parsing.dir/build.make CMakeFiles/phase2_l2_parsing.dir/examples/phase2_l2_parsing.cpp.i
.PHONY : examples/phase2_l2_parsing.cpp.i

examples/phase2_l2_parsing.s: examples/phase2_l2_parsing.cpp.s
.PHONY : examples/phase2_l2_parsing.s

# target to generate assembly for a file
examples/phase2_l2_parsing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase2_l2_parsing.dir/build.make CMakeFiles/phase2_l2_parsing.dir/examples/phase2_l2_parsing.cpp.s
.PHONY : examples/phase2_l2_parsing.cpp.s

examples/phase3_fdb_usage.o: examples/phase3_fdb_usage.cpp.o
.PHONY : examples/phase3_fdb_usage.o

# target to build an object file
examples/phase3_fdb_usage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase3_fdb_usage.dir/build.make CMakeFiles/phase3_fdb_usage.dir/examples/phase3_fdb_usage.cpp.o
.PHONY : examples/phase3_fdb_usage.cpp.o

examples/phase3_fdb_usage.i: examples/phase3_fdb_usage.cpp.i
.PHONY : examples/phase3_fdb_usage.i

# target to preprocess a source file
examples/phase3_fdb_usage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase3_fdb_usage.dir/build.make CMakeFiles/phase3_fdb_usage.dir/examples/phase3_fdb_usage.cpp.i
.PHONY : examples/phase3_fdb_usage.cpp.i

examples/phase3_fdb_usage.s: examples/phase3_fdb_usage.cpp.s
.PHONY : examples/phase3_fdb_usage.s

# target to generate assembly for a file
examples/phase3_fdb_usage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase3_fdb_usage.dir/build.make CMakeFiles/phase3_fdb_usage.dir/examples/phase3_fdb_usage.cpp.s
.PHONY : examples/phase3_fdb_usage.cpp.s

examples/phase4_interface_vlan_config.o: examples/phase4_interface_vlan_config.cpp.o
.PHONY : examples/phase4_interface_vlan_config.o

# target to build an object file
examples/phase4_interface_vlan_config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase4_interface_vlan_config.dir/build.make CMakeFiles/phase4_interface_vlan_config.dir/examples/phase4_interface_vlan_config.cpp.o
.PHONY : examples/phase4_interface_vlan_config.cpp.o

examples/phase4_interface_vlan_config.i: examples/phase4_interface_vlan_config.cpp.i
.PHONY : examples/phase4_interface_vlan_config.i

# target to preprocess a source file
examples/phase4_interface_vlan_config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase4_interface_vlan_config.dir/build.make CMakeFiles/phase4_interface_vlan_config.dir/examples/phase4_interface_vlan_config.cpp.i
.PHONY : examples/phase4_interface_vlan_config.cpp.i

examples/phase4_interface_vlan_config.s: examples/phase4_interface_vlan_config.cpp.s
.PHONY : examples/phase4_interface_vlan_config.s

# target to generate assembly for a file
examples/phase4_interface_vlan_config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase4_interface_vlan_config.dir/build.make CMakeFiles/phase4_interface_vlan_config.dir/examples/phase4_interface_vlan_config.cpp.s
.PHONY : examples/phase4_interface_vlan_config.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netflow_app.dir/build.make CMakeFiles/netflow_app.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netflow_app.dir/build.make CMakeFiles/netflow_app.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netflow_app.dir/build.make CMakeFiles/netflow_app.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... netflow_app"
	@echo "... netflow_port_lib"
	@echo "... netflow_switching_lib"
	@echo "... phase1_packet_usage"
	@echo "... phase2_l2_parsing"
	@echo "... phase3_fdb_usage"
	@echo "... phase4_interface_vlan_config"
	@echo "... examples/phase1_packet_usage.o"
	@echo "... examples/phase1_packet_usage.i"
	@echo "... examples/phase1_packet_usage.s"
	@echo "... examples/phase2_l2_parsing.o"
	@echo "... examples/phase2_l2_parsing.i"
	@echo "... examples/phase2_l2_parsing.s"
	@echo "... examples/phase3_fdb_usage.o"
	@echo "... examples/phase3_fdb_usage.i"
	@echo "... examples/phase3_fdb_usage.s"
	@echo "... examples/phase4_interface_vlan_config.o"
	@echo "... examples/phase4_interface_vlan_config.i"
	@echo "... examples/phase4_interface_vlan_config.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
